name: base
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - archspec=0.2.5
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - conda=25.3.0
  - conda-libmamba-solver=25.3.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - distro=1.9.0
  - fmt=11.1.4
  - frozendict=2.4.6
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libarchive=3.7.7
  - libcurl=8.13.0
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libmamba=2.1.1
  - libmambapy=2.1.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libsolv=0.7.32
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.1.1
  - menuinst=2.2.0
  - ncurses=6.5
  - nlohmann_json=3.11.3
  - openssl=3.5.0
  - packaging=25.0
  - pip=25.1.1
  - platformdirs=4.3.8
  - pluggy=1.5.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.12.10
  - python_abi=3.12
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.8
  - setuptools=80.1.0
  - simdjson=3.12.3
  - tk=8.6.13
  - tqdm=4.67.1
  - truststore=0.10.1
  - urllib3=2.4.0
  - wheel=0.45.1
  - yaml-cpp=0.8.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - attrs==25.3.0
      - click==8.2.1
      - cloudpickle==3.1.1
      - dm-tree==0.1.9
      - farama-notifications==0.0.4
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - gymnasium==1.0.0
      - jinja2==3.1.6
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - lz4==4.4.4
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.4
      - networkx==3.5
      - numpy==2.3.1
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - ormsgpack==1.7.0
      - pandas==2.3.1
      - pillow==11.3.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytorch-triton==3.4.0+gitf7888497
      - pytz==2025.2
      - pyyaml==6.0.2
      - ray==2.47.1
      - referencing==0.36.2
      - rpds-py==0.26.0
      - scipy==1.16.0
      - six==1.17.0
      - sympy==1.14.0
      - tensorboardx==2.6.4
      - torch==2.9.0.dev20250908+cu128
      - torch-geometric==2.6.1
      - torchaudio==2.8.0.dev20250908+cu128
      - torchvision==0.24.0.dev20250908+cu128
      - triton==3.3.1
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - wrapt==1.17.2
      - yarl==1.20.1
prefix: /home/bert/miniforge3
